### ISSUE TITLE
Settings not changing

### ISSUE THREAD

**Issue by Dhruv80576** [fossasia/badge-magic-android#1067] opened 2024-11-03 06:03 UTC
Tried changing language but it didn't change. After going through the code i found that its not implemented yet and i would like to work on it.
Attaching video for the issue.

https://github.com/user-attachments/assets/cf3917a6-5c11-466b-b39d-aaa52ec471a1

Please assign it to me.

**Comment by adityastic** [comment] 2024-11-03 13:20
Duplicate of: https://github.com/fossasia/badgemagic-android/issues/927

**Closed as not planned** 2024-11-03 13:20 UTC
