### ISSUE TITLE
Make badge preview fixes

### ISSUE THREAD

**Issue by yatri1609** [fossasia/badge-magic-android#168] opened 2019-04-06 13:32 UTC
**Describe the feature you'd like**
make badge preview fixed and other items scroll-able only when the screen is in portrait mode.

**Additional context**
It will allow user to see the preview all the time.

**Would you like to work on the issue?**
YES

**Comment by adityastic** [comment] 2019-04-10 13:44
Hey, can you explain me what the issue is about?

**Comment by yatri1609** [comment] 2019-04-11 18:54
Currently when the screen is vertical the badge preview screen also gets scrolled when we scroll for options and all so I think making it fixed for portrait mode would be a good idea.

**Comment by adityastic** [comment] 2019-04-11 23:53
@yatri1609 oh ok. It is fixed in the latest PR by yash

**Closed** 2019-04-13 18:41 UTC
